<a href="https://colab.research.google.com/github/XTruong1511/TH_DeepLaening/blob/main/TH_Deep_B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

###1. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)

In [ ]:
import numpy as np

array = np.random.randint(0, 21, size=(3, 3))
print("Mảng ngẫu nhiên 3x3:")
print(array)
check_nonzero = np.all(array != 0)

print(f"\nTất cả các phần tử trong mảng có khác 0 không? {check_nonzero}")

Mảng ngẫu nhiên 3x3:
[[ 9  9 20]
 [20 16 14]
 [20 12  9]]

Tất cả các phần tử trong mảng có khác 0 không? True


###2. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)

In [ ]:
import numpy as np

array_any = np.random.randint(0, 21, size=(3, 3))
print("Mảng ngẫu nhiên 3x3:")
print(array_any)

exists_nonzero = np.any(array_any != 0)

print(f"\nCó tồn tại phần tử nào trong mảng khác 0 không? {exists_nonzero}")

Mảng ngẫu nhiên 3x3:
[[19 15  5]
 [17  2  6]
 [20 13 19]]

Có tồn tại phần tử nào trong mảng khác 0 không? True


###3. Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater, numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [ ]:
import numpy as np

# Khởi tạo mảng 1 chiều
a1 = np.array([1, 5, 10])
b1 = np.array([2, 5, 8])

print("Mảng 1D a:", a1)
print("Mảng 1D b:", b1)

print("\nSo sánh 1 chiều:")
print("a > b  (greater):      ", np.greater(a1, b1))
print("a >= b (greater_equal):", np.greater_equal(a1, b1))
print("a < b  (less):         ", np.less(a1, b1))
print("a <= b (less_equal):   ", np.less_equal(a1, b1))

Mảng 1D a: [ 1  5 10]
Mảng 1D b: [2 5 8]

So sánh 1 chiều:
a > b  (greater):       [False False  True]
a >= b (greater_equal): [False  True  True]
a < b  (less):          [ True False False]
a <= b (less_equal):    [ True  True False]


In [ ]:
# Khởi tạo mảng 2 chiều
a2 = np.array([[1, 2], [3, 4]])
b2 = np.array([[0, 2], [5, 4]])

print("Mảng 2D a:\n", a2)
print("Mảng 2D b:\n", b2)

print("\nSo sánh 2 chiều (greater_equal):")
print(np.greater_equal(a2, b2))

print("\nSo sánh 2 chiều (less):")
print(np.less(a2, b2))

Mảng 2D a:
 [[1 2]
 [3 4]]
Mảng 2D b:
 [[0 2]
 [5 4]]

So sánh 2 chiều (greater_equal):
[[ True  True]
 [False  True]]

So sánh 2 chiều (less):
[[False False]
 [ True False]]


###4. Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [ ]:
import numpy as np

ones = np.ones(10)
zeros = np.zeros(10)

fives = np.ones(10) * 5
result = np.concatenate([ones, zeros, fives])

print("Mảng kết quả:")
print(result)
print(f"Kích thước mảng: {result.size}")

Mảng kết quả:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]
Kích thước mảng: 30


###5. Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]

In [ ]:
import numpy as np

even_array = np.arange(30, 71, 2)

print("Mảng các số nguyên chẵn từ 30 đến 70:")
print(even_array)

Mảng các số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


###6. Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0) (Tìm hiểu hàm identity của numpy)

In [ ]:
import numpy as np

identity_matrix = np.identity(3)

print("Ma trận đơn vị 3x3:")
print(identity_matrix)

Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###7. Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử đầu và cuối

In [ ]:
import numpy as np

array_7 = np.linspace(15, 55, 10)

print("Mảng đầy đủ:")
print(array_7)

filtered_array = array_7[1:-1]

print("\nCác giá trị ngoại trừ phần tử đầu và cuối:")
print(filtered_array)

Mảng đầy đủ:
[15.         19.44444444 23.88888889 28.33333333 32.77777778 37.22222222
 41.66666667 46.11111111 50.55555556 55.        ]

Các giá trị ngoại trừ phần tử đầu và cuối:
[19.44444444 23.88888889 28.33333333 32.77777778 37.22222222 41.66666667
 46.11111111 50.55555556]


###8. Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20] và đổi dấu những số nằm trong khoảng [9, 15]

In [ ]:
import numpy as np

array_8 = np.linspace(0, 20, 20)

print("Mảng ban đầu:")
print(array_8)

array_8[(array_8 >= 9) & (array_8 <= 15)] *= -1

print("\nMảng sau khi đổi dấu các phần tử trong khoảng [9, 15]:")
print(array_8)

Mảng ban đầu:
[ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]

Mảng sau khi đổi dấu các phần tử trong khoảng [9, 15]:
[  0.           1.05263158   2.10526316   3.15789474   4.21052632
   5.26315789   6.31578947   7.36842105   8.42105263  -9.47368421
 -10.52631579 -11.57894737 -12.63157895 -13.68421053 -14.73684211
  15.78947368  16.84210526  17.89473684  18.94736842  20.        ]


###9. Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]

In [ ]:
import numpy as np

matrix_3x4 = np.random.randint(10, 22, size=(3, 4))

print("Ma trận 3x4 với giá trị trong khoảng [10, 21]:")
print(matrix_3x4)

Ma trận 3x4 với giá trị trong khoảng [10, 21]:
[[10 15 16 10]
 [14 14 14 18]
 [21 19 12 18]]


### 10. Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong có giá trị 0

In [ ]:
import numpy as np

border_matrix = np.ones((10, 10), dtype=int)

border_matrix[1:-1, 1:-1] = 0

print("Ma trận 10x10 với biên bằng 1 và bên trong bằng 0:")
print(border_matrix)

Ma trận 10x10 với biên bằng 1 và bên trong bằng 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


###11. Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chính là 1, 2, 3, 4, 5. (tìm hiểu hàm diag của numpy)

In [ ]:
import numpy as np

diagonal_values = [1, 2, 3, 4, 5]
diagonal_matrix = np.diag(diagonal_values)

print("Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:")
print(diagonal_matrix)

Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###12. Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum của numpy)

In [ ]:
import numpy as np

array_3d = np.random.randint(1, 10, size=(3, 3, 3))
print("Mảng 3x3x3:")
print(array_3d)

sum_rows = np.sum(array_3d, axis=2)

sum_cols = np.sum(array_3d, axis=1)

print("\nTổng theo mỗi dòng (mỗi hàng là kết quả của một lát cắt 3x3):")
print(sum_rows)

print("\nTổng theo mỗi cột (mỗi hàng là kết quả của một lát cắt 3x3):")
print(sum_cols)

Mảng 3x3x3:
[[[2 4 1]
  [1 5 2]
  [9 3 1]]

 [[8 3 5]
  [1 9 5]
  [5 8 2]]

 [[6 6 5]
  [9 4 9]
  [7 6 6]]]

Tổng theo mỗi dòng (mỗi hàng là kết quả của một lát cắt 3x3):
[[ 7  8 13]
 [16 15 15]
 [17 22 19]]

Tổng theo mỗi cột (mỗi hàng là kết quả của một lát cắt 3x3):
[[12 12  4]
 [14 20 12]
 [22 16 20]]


### 13. Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)

In [ ]:
import numpy as np

v1 = np.random.randint(1, 10, 10)
v2 = np.random.randint(1, 10, 10)

print("Vector 1:", v1)
print("Vector 2:", v2)

inner_product = np.dot(v1, v2)

print(f"\nInner product của 2 vector là: {inner_product}")

Vector 1: [1 1 5 3 8 5 9 7 2 4]
Vector 2: [9 1 6 6 3 9 4 2 5 9]

Inner product của 2 vector là: 223


### 14. Tạo ma trận A= 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dòng của ma trận A

In [ ]:
import numpy as np

A = np.random.randint(1, 10, size=(4, 3))
y = np.random.randint(1, 10, size=3)

print("Ma trận A (4x3):")
print(A)
print("\nVector y (size 3):")
print(y)

result_14 = A + y

print("\nKết quả sau khi thêm y vào từng dòng của A:")
print(result_14)

Ma trận A (4x3):
[[7 6 5]
 [6 4 9]
 [3 4 3]
 [1 7 5]]

Vector y (size 3):
[2 1 6]

Kết quả sau khi thêm y vào từng dòng của A:
[[ 9  7 11]
 [ 8  5 15]
 [ 5  5  9]
 [ 3  8 11]]


### 15. Viết chương trình Pandas để cộng, trừ, nhân, chia 2 Series : [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [ ]:
import pandas as pd

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:\n", s1)
print("\nSeries 2:\n", s2)

print("\nCộng:")
print(s1 + s2)

print("\nTrừ:")
print(s1 - s2)

print("\nNhân:")
print(s1 * s2)

print("\nChia:")
print(s1 / s2)

Series 1:
 0     2
1     4
2     6
3     8
4    10
dtype: int64

Series 2:
 0     1
1     3
2     5
3     7
4    10
dtype: int64

Cộng:
0     3
1     7
2    11
3    15
4    20
dtype: int64

Trừ:
0    1
1    1
2    1
3    1
4    0
dtype: int64

Nhân:
0      2
1     12
2     30
3     56
4    100
dtype: int64

Chia:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64
